Feedback
spbu-coding/1-Lev0nid pull request #1
Opened 2020-09-29 08:20 UTC by KutuevVladimir

:wave:! GitHub Classroom created this pull request as a place for your teacher to leave feedback on your work. It will update automatically. **Don’t close or merge this pull request**, unless you’re instructed to do so by your teacher.

In this pull request, your teacher can leave comments and feedback on your code. Click the **Subscribe** button to be notified if that happens.

Click the **Files changed** or **Commits** tab to see all of the changes pushed to `master` since the assignment started. Your teacher can see this too.

<details>
<summary>
<strong>Notes for teachers</strong>
</summary>

Use this PR to leave feedback. Here are some tips:

- Click the **Files changed** tab to see all of the changes pushed to `master` since the assignment started. To leave comments on specific lines of code, put your cursor over a line of code and click the blue **+** (plus sign). To learn more about comments, read “[Commenting on a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request)”.
- Click the **Commits** tab to see the commits pushed to `master`. Click a commit to see specific changes.
- If you turned on autograding, then click the **Checks** tab to see the results.
- This page is an overview. It shows commits, line comments, and general comments. You can leave a general comment below.

For more information about this pull request, read “[Leaving assignment feedback in GitHub](https://classroom.github.com/help/leaving-feedback-in-github)”.
</details>

2020-09-29 18:19 UTC, Lev0nid commented
Скриншот с тестом
![image](https://user-images.githubusercontent.com/66315146/94599646-66083d80-0299-11eb-9c1d-0f36d5322d55.png)

2020-10-03 23:15 UTC, EgorkaKulikov requested changes

2020-10-03 23:15 UTC, EgorkaKulikov commented on src/main.c
> +    double results[6][2];
Мне кажется, в строках 27-29 константа 6 должна меняться синхронно. То есть каждое изменение просит изменить три места. Это нехорошо. Нужно просто создать константу и её использовать.

2020-10-03 23:15 UTC, EgorkaKulikov commented on src/main.c
> +    scanf("%lf%lf", &leftBorder, &rightBorder);
А где валидация параметров? Что мы действительно попали в интервал [0, PI]?
В случае интервала [PI, 2PI] ваша программа начнёт считать интеграл вместо того, чтобы вернуть ошибку о некорректных аргументах.
Это установленный сценарий некорректной работы программы.

2020-10-03 23:15 UTC, EgorkaKulikov commented on src/main.c
> +#define _CRT_SECURE_NO_WARNINGS
такое лучше единожды прописать в настройках проекта, а не в каждом его файле

2020-10-03 23:15 UTC, EgorkaKulikov commented on src/main.c
> +        subgraphArea += sin(leftBorder + (i - 1) * rectangleSize) + 4 * sin(leftBorder + i * rectangleSize) + sin(leftBorder + (i + 1) * rectangleSize);
Слишком длинные строки затрудняют чтение программы. Нет какого-то "норматива", но лучше избегать строк, не влезающих в среднестатистический экран и переносить текст на новую.

2020-10-03 23:15 UTC, EgorkaKulikov commented on src/main.c
> +double areaBySimpson(double leftBorder, double rightBorder, int amountOfRectangles) {
Как правило, рекомендуют, чтобы название метода содержало глагол. Что-то вроде "вычислить по формуле Симпсона"

2020-10-03 23:16 UTC, EgorkaKulikov commented
К сожалению, тут целых два сценария некорректной работы: падение билдов и отсутствие валидации параметров. Это -3 балла по правилам. За остальное не снижаю.
Оценка 7 из 10

2020-10-12 12:47 UTC, EgorkaKulikov commented
Я не понимаю, откуда в этом пулреквесте 42 файла. Такого не должно быть, ведь мы добавляем всего один.

2020-10-12 15:49 UTC, Lev0nid commented
Кажется, это CLion добавляет файлы...

2020-10-13 20:39 UTC, EgorkaKulikov commented
А разве то, что CLion что-то добавляет, означает, что это надо коммитить?

2020-10-15 13:12 UTC, Lev0nid commented
только, как я понял, гитигнор надо было раньше писать...

2020-10-19 18:56 UTC, EgorkaKulikov commented
Какой-то хлам, кажется, всё равно остался. Но и ладно. Главное, надеюсь, остался ценный опыт.

2020-10-19 18:56 UTC, merged